services:
  db:
    restart: always
    platform: linux/amd64
    container_name: demo-postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: demo-pgadmin #you can change this
    depends_on:
      - db
    ports:
      - "5051:80"
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
