# Generated by Django 4.2.18 on 2025-01-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="legiscan_bill_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
