# Generated by Django 4.2.18 on 2025-01-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0003_bill_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="title",
            new_name="bill_title",
        ),
    ]
