# Generated by Django 4.2.18 on 2025-02-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0006_userkeyword_created_userkeyword_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="userbillinteraction",
            options={"ordering": ["modified"]},
        ),
        migrations.AlterModelOptions(
            name="userkeyword",
            options={"ordering": ["created"]},
        ),
        migrations.AddField(
            model_name="bill",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="bills", to="bill.tag"
            ),
        ),
    ]
