# Generated by Django 4.2.19 on 2025-02-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_alter_bill_admin_stance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbillinteraction',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
