# Generated by Django 4.2.19 on 2025-11-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0010_billanalysis"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billanalysis",
            options={
                "verbose_name": "Bill Analysis",
                "verbose_name_plural": "Bill Analyses",
            },
        ),
    ]
