# Generated by Django 4.2.19 on 2026-04-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0011_alter_billanalysis_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
