# Generated by Django 4.2.19 on 2026-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0012_alter_bill_bill_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_session_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userbillinteraction",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
