# Generated by Django 4.2.19 on 2025-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("horizontal", "Horizontal"),
                    ("vertical", "Vertical"),
                    ("square", "Square"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
