# Generated by Django 4.2.19 on 2025-02-27 01:24

import citext.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=citext.fields.CIEmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
